### ISSUE TITLE
Search Async Items after 2 letters.

### ISSUE THREAD

**Issue by 10terabyte** [rahmanrezaee/flutter_async_autocomplete#6]
Hello.
I am using this package and really good to use.
I am developing a flutter app and using this package for address search.
But I want to search address after user type 2 letters more.
But I cannot find option to set this.
I want your team support for this problem.
Thank you.

**Comment by 10terabyte** [comment]
Of course I can call api after type 2 letters.
But this package shows circle spinner when type address.
Want to show this when call api only.
Thank you.
![Screenshot_1677684079](https://user-images.githubusercontent.com/117177084/222183716-2073810a-ac0f-4bbd-87bc-60b88e17acdb.png)

**Comment by rahmanrezaee** [comment]
@FullStack1106 Thanks for reporting ok I will add an option to it.
