### ISSUE TITLE
Crash on updateSuggestions

### ISSUE THREAD

**Issue by baer999** [rahmanrezaee/flutter_async_autocomplete#9]
_TypeError
 
flutter_async_autocomplete.dart in _AsyncAutocompleteState.updateSuggestions

Regression
Null check operator used on a null value

_TypeError
Null check operator used on a null value

Crashed in non-app: framework.dart in State.setState within flutter
System
flutter_async_autocomplete.dart in _AsyncAutocompleteState.updateSuggestions at line 215 within flutter_async_autocomplete
In App
flutter_async_autocomplete.dart in _AsyncAutocompleteState.initState.<fn> at line 153 within flutter_async_autocomplete
In App
Called from: change_notifier.dart in ChangeNotifier.notifyListeners within flutter

is there any idea how to fix it or is it maybe a bug in library?

**Comment by rahmanrezaee** [comment]
@baer999 please fix the issue and make a pull request to merge with the master thanks.

**Comment by baer999** [comment]
Hi @rahmanrezaee yes tried already to check but line 215 makes no sense for me to having null check error?!
`setState(() => _isLoading = true);`
Do you have any idea? If yes, sure I would create a pull request : )
